"""
backend/routers/query.py
─────────────────────────
Primary API router for query execution and session history management.

This router has been refactored to delegate all core query orchestration,
stream processing, and sandbox execution to the `QueryOrchestrator` service.
It is now under 150 lines, adhering to the Single Responsibility Principle.
"""
import os
import json
import uuid
from typing import Optional
from fastapi import APIRouter, HTTPException, BackgroundTasks, Request, Depends
from fastapi.responses import FileResponse, StreamingResponse
from pydantic import BaseModel

import backend.config as config
from backend.models.schemas import QueryRequest
import backend.services.history_db as db
from backend.services.query_orchestrator import QueryOrchestrator
from backend.services.security_manager import verify_token

router = APIRouter(prefix="/api", dependencies=[Depends(verify_token)])

# Workspace root paths
WORKSPACE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CHARTS_DIR = os.path.join(WORKSPACE_ROOT, "data", "charts")


@router.post("/query")
def run_query(req: QueryRequest, background_tasks: BackgroundTasks, request: Request):
    """
    POST route returning a StreamingResponse that sends SSE chunks of progress updates
    and final query results generated by the QueryOrchestrator.
    """
    workspace_id = request.headers.get("x-workspace-id")
    orchestrator = QueryOrchestrator()
    
    return StreamingResponse(
        orchestrator.execute_query_stream(req, background_tasks, workspace_id),
        media_type="text/event-stream"
    )


@router.get("/conversations")
def get_conversations(request: Request):
    """
    Returns list of active conversations for the authenticated user.
    """
    workspace_id = request.headers.get("x-workspace-id")
    user_id = None
    auth_header = request.headers.get("Authorization")
    if auth_header and auth_header.startswith("Bearer "):
        try:
            token = auth_header.split(" ")[1]
            from backend.services.security_manager import decode_jwt
            payload = decode_jwt(token)
            user_id = payload.get("user_id")
            if payload.get("role") == "Super Admin":
                user_id = None
        except Exception:
            pass

    return db.list_conversations(workspace_id, user_id)


@router.get("/conversations/search")
def search_conversations(q: str):
    """
    Fuzzy search over past conversation summaries and questions.
    """
    return db.search_conversations(q)


@router.get("/conversation/{id}")
def get_conversation_details(id: str):
    """
    Returns complete detail of a conversation including formatted messages feed.
    """
    conv = db.get_conversation(id)
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found")
        
    messages = db.get_messages(id, limit=None)
    
    # Parse result previews and debug telemetry structures
    for msg in messages:
        if msg.get("result_preview"):
            try:
                msg["result"] = json.loads(msg["result_preview"])
            except Exception:
                msg["result"] = []
        else:
            msg["result"] = []
            
        if msg.get("debug_info"):
            try:
                msg["debug_info"] = json.loads(msg["debug_info"])
            except Exception:
                msg["debug_info"] = None
                
    return {
        "conversation": conv,
        "messages": messages
    }


@router.delete("/conversation/{id}")
def delete_conversation_api(id: str):
    """
    Removes a conversation and its messages history.
    """
    db.delete_conversation(id)
    return {"status": "success", "message": "Conversation deleted."}


@router.get("/chart/html")
def get_chart_html(id: str | None = None):
    """
    Retrieves interactive Plotly HTML visualization.
    If no ID is provided, returns the latest static chart.html.
    """
    if id:
        safe_id = os.path.basename(id)
        path = os.path.join(CHARTS_DIR, f"{safe_id}.html")
        if os.path.exists(path):
            return FileResponse(path, media_type="text/html")
    
    # Fallback to static chart.html
    static_path = os.path.join(CHARTS_DIR, "chart.html")
    if os.path.exists(static_path):
        return FileResponse(static_path, media_type="text/html")

    raise HTTPException(status_code=404, detail="No interactive chart available.")


@router.get("/chart/plotly.min.js")
@router.get("/chart/html/plotly.min.js")
def get_plotly_js():
    """
    Serves local Plotly JavaScript library for instant offline rendering without CDN latency.
    """
    js_path = os.path.join(CHARTS_DIR, "plotly.min.js")
    if os.path.exists(js_path):
        return FileResponse(js_path, media_type="application/javascript")
    raise HTTPException(status_code=404, detail="Plotly JS file not found.")


@router.get("/chart/png")
def get_chart_png(id: str | None = None):
    """
    Retrieves static PNG visualization.
    """
    if id:
        safe_id = os.path.basename(id)
        path = os.path.join(CHARTS_DIR, f"{safe_id}.png")
        if not os.path.exists(path):
            import backend.services.chart_factory as cf
            cf.generate_png_on_demand(CHARTS_DIR, safe_id)
        if os.path.exists(path):
            return FileResponse(path, media_type="image/png")
    
    # Fallback static png
    static_png = os.path.join(CHARTS_DIR, "chart.png")
    if os.path.exists(static_png):
        return FileResponse(static_png, media_type="image/png")

    raise HTTPException(status_code=404, detail="No static chart available.")
