"use client";

import { useEffect, useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { ApiClient } from "@/lib/apiClient";

export default function VisualizationsPage() {
  const [hasChart, setHasChart] = useState(false);
  const [loading, setLoading] = useState(true);

  const checkChart = async () => {
    try {
      const res = await ApiClient.request("/api/status");
      if (res.ok) {
        const data = await res.json();
        const chartRes = await ApiClient.request("/api/chart/html", { method: "HEAD" });
        setHasChart(chartRes.ok);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    checkChart();
  }, []);

  return (
    <DashboardLayout>
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-deep-navy tracking-tight">Data Visualizations</h1>
        <p className="text-sm text-on-surface-variant mt-1">
          View interactive plots and charts generated by your natural language queries.
        </p>
      </div>

      <div className="bg-surface-white border border-outline-variant/35 rounded-xl p-8 min-h-[500px] flex flex-col justify-center items-center shadow-sm">
        {loading ? (
          <div className="flex flex-col items-center gap-3 animate-pulse text-sm text-vibrant-blue font-bold">
            <span className="material-symbols-outlined animate-spin text-2xl">progress_activity</span>
            <span>Checking active visualizations...</span>
          </div>
        ) : hasChart ? (
          <div className="w-full space-y-6">
            <div className="flex justify-between items-center pb-4 border-b border-outline-variant/35">
              <h3 className="text-base font-bold text-deep-navy flex items-center gap-2">
                <span className="material-symbols-outlined text-vibrant-blue">bar_chart</span>
                Active Interactive Chart
              </h3>
              <div className="flex gap-2">
                <a
                  href="http://127.0.0.1:8000/api/chart/html"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-surface-container border border-outline-variant/30 text-xs font-bold py-1.5 px-3 rounded-lg hover:bg-surface-container-high transition-all flex items-center gap-1.5 cursor-pointer"
                >
                  <span className="material-symbols-outlined text-xs">open_in_new</span>
                  Open Fullscreen
                </a>
                <a
                  href="http://127.0.0.1:8000/api/chart/png"
                  download="chart.png"
                  className="bg-deep-navy text-white text-xs font-bold py-1.5 px-3 rounded-lg hover:bg-primary transition-all flex items-center gap-1.5 cursor-pointer shadow-xs"
                >
                  <span className="material-symbols-outlined text-xs">download</span>
                  Download PNG
                </a>
              </div>
            </div>
            
            <div className="w-full h-[550px] bg-white rounded-xl overflow-hidden border border-outline-variant/50 shadow-sm relative">
              <iframe
                src="http://127.0.0.1:8000/api/chart/html"
                className="w-full h-full border-none bg-white"
                title="Interactive Visual Plot"
              />
            </div>
          </div>
        ) : (
          <div className="text-center max-w-md flex flex-col items-center">
            <div className="w-16 h-16 rounded-full bg-primary-fixed/30 border border-outline-variant/30 flex items-center justify-center mb-6">
              <span className="material-symbols-outlined text-vibrant-blue text-3xl font-variation-settings-fill" style={{ fontVariationSettings: "'FILL' 1" }}>add_chart</span>
            </div>
            <h3 className="text-lg font-bold text-deep-navy mb-2">No Active Visualizations</h3>
            <p className="text-xs text-on-surface-variant leading-relaxed mb-6 font-semibold">
              Visualizations are auto-generated when you ask the Chat Analyst to draw plots.
              Try asking:
              <br />
              <span className="text-vibrant-blue italic font-bold">"Plot a line chart of sales values over time"</span>.
            </p>
            <a
              href="/query"
              className="bg-deep-navy text-white text-xs font-bold py-2.5 px-6 rounded-lg hover:bg-primary transition-all shadow-xs cursor-pointer"
            >
              Go to Chat Analyst
            </a>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
